export { PlatformAdapter, type AdapterStatus } from "./adapter.js";
export type { PlatformMetadata } from "./metadata.js";
export { MessageConverter } from "./conversion.js";
export { AdapterRegistry, registerBuiltinAdapterFactories, type AdapterFactory } from "./registry.js";
export {
  validateAdapterConfig,
  type AdapterConfigBase,
  type OneBot11AdapterConfig,
} from "./config.js";
export {
  OneBot11Adapter,
  type Ob11FileResult,
  type Ob11GetMsgResult,
  type Ob11GetForwardMsgResult,
  type Ob11SendMsgResult,
  type Ob11LoginInfo,
  type Ob11FriendRequestEvent,
  type Ob11GroupRequestEvent,
  type Ob11NoticeEvent,
  type Ob11GroupInfo,
  type Ob11GroupMemberInfo,
  // Phase 7 extended types
  type Ob11ForwardMsgNode,
  type Ob11ForwardMsgResult,
  type Ob11GroupMsgHistoryItem,
  type Ob11GroupMsgHistoryResult,
  type Ob11OcrTextDetection,
  type Ob11OcrResult,
  type Ob11GroupFileUrlResult,
  type Ob11DownloadFileResult,
  type Ob11CheckUrlSafelyResult,
  type Ob11GroupAtAllRemainResult,
  type Ob11GroupHonorInfo,
  type Ob11GroupFile,
  type Ob11GroupFileListResult,
  type Ob11GroupFileSystemInfo,
  type Ob11EssenceMsg,
  type Ob11EssenceMsgListResult,
  type Ob11GroupNotice,
  type Ob11GroupNoticeListResult,
} from "./implementations/onebot11-adapter.js";
export {
  QQOfficialAdapter,
  type QQOfficialAdapterConfig,
  type QQOfficialMediaType,
  type QQOfficialRichMediaUploadResult,
  type QQOfficialMarkdownTemplate,
  type QQOfficialMarkdownCustom,
  type QQOfficialArkMessage,
  type QQOfficialEmbed,
  type QQOfficialMediaField,
  type QQOfficialButtonPermission,
  type QQOfficialButtonAction,
  type QQOfficialButtonRender,
  type QQOfficialButton,
  type QQOfficialButtonRow,
  type QQOfficialKeyboard,
  type QQOfficialReactionUser,
  type QQOfficialReactionUsersResult,
  type QQOfficialSendOptions,
  type QQOfficialSendMessageResult,
  // Phase 2: Guild / Channel / Member / Role / Announces / Schedule types
  type QQOfficialUser,
  type QQOfficialGuild,
  type QQOfficialMember,
  type QQOfficialRole,
  type QQOfficialChannel,
  type QQOfficialChannelCreateOptions,
  type QQOfficialChannelUpdateOptions,
  type QQOfficialChannelPermissions,
  type QQOfficialAnnounce,
  type QQOfficialAnnounceCreateOptions,
  type QQOfficialSchedule,
  type QQOfficialScheduleOptions,
  type QQOfficialModifyMemberOptions,
  type QQOfficialApiPermissionIdentify,
  type QQOfficialApiPermissionDemand,
  type QQOfficialApiPermissionDemandOptions,
  type QQOfficialOnlineNums,
  // Phase 4: Gateway / Message / Role CRUD / Pins / Speak / Forum / Audio types
  type QQOfficialGateway,
  type QQOfficialGatewayBot,
  type QQOfficialChannelMessage,
  type QQOfficialListMessagesOptions,
  type QQOfficialPatchMessageOptions,
  type QQOfficialRoleOptions,
  type QQOfficialRoleCreateResult,
  type QQOfficialPinsListResult,
  type QQOfficialPinsResult,
  type QQOfficialSpeakPrivilegeSettings,
  type QQOfficialMessageSetting,
  type QQOfficialThread,
  type QQOfficialThreadDetail,
  type QQOfficialThreadListResult,
  type QQOfficialComment,
  type QQOfficialCommentListResult,
  type QQOfficialAudioControl,
  // Phase 5: Sandbox / Sharding / Event subscription config types
  type QQOfficialIntentName,
} from "./implementations/qqofficial-adapter.js";
